//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BinGoAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Director { get; set; }
        public string Actor { get; set; }
        public string Language { get; set; }
        public int Type { get; set; }
        public string District { get; set; }
        public string Date { get; set; }
        public string Keyword { get; set; }
        public int Picture { get; set; }
        public int Time { get; set; }
        public Nullable<decimal> Score { get; set; }
    }
}
